<?xml version="1.0" encoding="utf-8"?>
<?AutomationStudio FileVersion="4.9"?>
<Program SubType="ANSIC" xmlns="http://br-automation.co.at/AS/Program">
  <Files>
    <File Private="true">testSuite.var</File>
    <File Description="Handling of program and test suite">testSuite.c</File>
    <File Description="Helper functions for nanoPB testing">test_helpers.c</File>
    <File Description="Comprehensive nanoPB library tests">testSet_NanoPB.c</File>
    <File Description="Enhanced nanoPB tests with real proto files">testSet_NanoPB_Enhanced.c</File>
    <File Description="Generated nanoPB header from test_messages.proto">test_messages.pb.h</File>
    <File Description="Generated nanoPB implementation from test_messages.proto">test_messages.pb.c</File>
    <File Description="Auto generated code">autoGeneratedFile.c</File>
    <File>pb.h</File>
  </Files>
</Program>