(* Generated ST Types from iot_sensors.proto *)
(* Generated by nanoPB Simple Class-Based ST Generator *)
(* Uses nanoPB ProtoFile/Message/Field analysis via composition *)
(* Include protobuf_base.typ for base protobuf types *)

(* Message: SensorReading *)
TYPE ProtoSensorReading :
		STRUCT
		has_sensorId : BOOL;  (* nanoPB optional field presence indicator *)
		sensorId : DINT;
		has_temperature : BOOL;  (* nanoPB optional field presence indicator *)
		temperature : REAL;
		has_humidity : BOOL;  (* nanoPB optional field presence indicator *)
		humidity : REAL;
		has_alarmActive : BOOL;  (* nanoPB optional field presence indicator *)
		alarmActive : BOOL;
		has_location : BOOL;  (* nanoPB optional field presence indicator *)
		location : STRING[255];
		has_timestamp : BOOL;  (* nanoPB optional field presence indicator *)
		timestamp : LINT;
		readings : ARRAY[0..9] OF REAL;
		readings_count : UINT;  (* Number of valid elements *)
	END_STRUCT;
END_TYPE

(* Message: ControlCommand *)
TYPE ProtoControlCommand :
		STRUCT
		has_commandId : BOOL;  (* nanoPB optional field presence indicator *)
		commandId : DINT;
		has_commandName : BOOL;  (* nanoPB optional field presence indicator *)
		commandName : STRING[255];
		parameters : ARRAY[0..9] OF REAL;
		parameters_count : UINT;  (* Number of valid elements *)
		has_urgent : BOOL;  (* nanoPB optional field presence indicator *)
		urgent : BOOL;
		has_targetDevice : BOOL;  (* nanoPB optional field presence indicator *)
		targetDevice : DINT;
		has_timestamp : BOOL;  (* nanoPB optional field presence indicator *)
		timestamp : LINT;
	END_STRUCT;
END_TYPE

(* Message: SystemStatus *)
TYPE ProtoSystemStatus :
		STRUCT
		lastReading : ProtoSensorReading;
		has_online : BOOL;  (* nanoPB optional field presence indicator *)
		online : BOOL;
		has_cpuUsage : BOOL;  (* nanoPB optional field presence indicator *)
		cpuUsage : REAL;
		has_memoryUsage : BOOL;  (* nanoPB optional field presence indicator *)
		memoryUsage : REAL;
		has_activeConnections : BOOL;  (* nanoPB optional field presence indicator *)
		activeConnections : DINT;
		errorMessages : ARRAY[0..9] OF STRING[255];
		errorMessages_count : UINT;  (* Number of valid elements *)
		has_systemName : BOOL;  (* nanoPB optional field presence indicator *)
		systemName : STRING[255];
	END_STRUCT;
END_TYPE
